# Generated by Django 4.1 on 2022-09-06 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(db_index=True, help_text='Укажите название банка', max_length=30, unique=True, verbose_name='Название банка')),
                ('term_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10, message='Минимальный срок: 10')], verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30, message='Минимальный срок: 30')], verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.FloatField(validators=[django.core.validators.MinValueValidator(1.8, message='Минимальная ставка: 1.8')], verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(validators=[django.core.validators.MaxValueValidator(9.8, message='Минимальная ставка: 9.8')], verbose_name='Ставка, ДО')),
                ('payment_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000, message='Минимальная ставка: 1000000')], verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000000, message='Минимальная ставка: 10000000')], verbose_name='Сумма кредита, ДО')),
            ],
            options={
                'verbose_name': 'Ипотечное предложения',
                'verbose_name_plural': 'Ипотечные предложения',
                'ordering': ('-bankname',),
            },
        ),
    ]
