# Generated by Django 4.1 on 2022-09-12 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_offer_payment_max_alter_offer_payment_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payment_max',
            field=models.PositiveIntegerField(help_text='Введите максимальную сумму кредита', validators=[django.core.validators.MaxValueValidator(10000000, message='Максимальная кредит: 10000000')], verbose_name='Сумма кредита, ДО'),
        ),
    ]
